spring:
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  mvc:
    static-path-pattern: /static/images/**
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: file:images/, classpath:/static
jwt:
  secret: sadjklasjdqwiojeqpwjdsakdjlsakjdlksndasndlnqwlkejpqwojpqodjskadnlasndlkasndqpwoejpasljdlkasjldsdfsdfsdfsdfasdasdqwewqeasda